# Generated by Django 3.2.7 on 2022-02-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20220214_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
